name: CI/CD pipeline

on:
    push:
      branches:
        - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install nodeJs
              uses: actions/setup-node@v4

            - name : install dependencies
              run: npm install
              
         #  - name: run tests
          #   run : |
         #       node server.js
        #        curl http://localhost:3000 

            - name: Deploy to EC2
              env:
                PRIVATE_KEY: "${{secrets.EC2_SSH_PRIVATE_KEY}}"
                HOST: "${{secrets.EC2_HOST}}"
                USER: "ubuntu"
              run: 
                |
                  echo "$PRIVATE_KEY" > privateKey.pem
                  chmod 600 privateKey.pem
                  scp -i -o StrictHostKeyChecking=no privateKey.pem -r ./* $USER@$HOST:/home/ubuntu/app

                  ssh -i -o StrictHostKeyChecking=no privateKey.pem $USER@$HOST << 'EOF'
                      cd /home/ubuntu/app
                      npm install
                      pm2 stop all
                      pm2 start server.js --name my-app 
                      EOF

        

